version: '3.8'

services: 
    back:
        image: cec-back:0.3
        restart: always
        ports: 
            - 4000:8080
        environment: 
            DATABASE_NAME: comoencasadb
            PROJECT_ID: comoencasa-289703
            REGION: us-central1
            INSTANCE_ID: comoencasa